server:
  port: 80

spring:
  application:
    name: com.invo.payment.service-order

eureka:
  client:
    #true表示向注册中心EurekaServer注册自己,默认为true
    register-with-eureka: true
    #表示是否从EurekaServer抓取已有的注册信息，默认为true。
    #单节点无所谓，但集群必须设置为才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

