server:
  port: 8003

spring:
  application:
    name: com.invo.payment.service-payment-hystrix
#  cloud:
#    zookeeper:
#      connect-string: 122.51.33.98:2181
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        hostname: 127.0.0.1
#        service-name: ${spring.application.name}
#        prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    #true表示向注册中心EurekaServer注册自己,默认为true
    register-with-eureka: true
    #表示是否从EurekaServer抓取已有的注册信息，默认为true。
    #单节点无所谓，但集群必须设置为才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#logging:
#  level:
#    #    feign log 以指定级别监控指定接口
#    com.invo.payment.service.PaymentService: debug
